### ISSUE TITLE
"Subset Domain" not doing anything?

### ISSUE THREAD

**Issue by banesullivan** [CUAHSI/nwm_subsetting#21]
I'm super excited to see v0.5 up and running! Though when I went to test it out, I get no response after trying to subset the domain (Safari and Chrome):

![2020-04-15 09 14 59](https://user-images.githubusercontent.com/22067021/79341329-9d587d00-7ef9-11ea-8fb7-de807822e03d.gif)

**Comment by Castronova** [comment]
@banesullivan  Can you try clicking directly on the text, e.g. v1.2.2 or v1.0? It appears that the button isn't being triggered when clicking on whitespace.

**Comment by Castronova** [comment]
Turns out the link element was not filling the entire div of the button. This has been fixed.

**Comment by banesullivan** [comment]
Can confirm all is working now! Thanks and great work!
